const tones = { coral:{label:'focus',dot:'#e56e56',tag:'#bc5642',bg:'#fce6df'}, gold:{label:'light',dot:'#d69c3c',tag:'#a77425',bg:'#faf0d8'}, blue:{label:'deep work',dot:'#4c86a8',tag:'#376b89',bg:'#e1eef5'}, green:{label:'personal',dot:'#60936c',tag:'#4d7657',bg:'#e5f1e7'} };
function dateKey(value = new Date()) { const d = new Date(value); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0,10); }
const todayKey = dateKey();
const starterTasks = [
  {id:1,title:'Morning walk',date:todayKey,time:'07:30',tone:'green',note:'A little fresh air before the day begins',done:true},
  {id:2,title:'Shape the project proposal',date:todayKey,time:'09:00',tone:'blue',note:'Outline the narrative, then make it simple',done:false},
  {id:3,title:'Lunch with Mia',date:todayKey,time:'12:30',tone:'gold',note:'The Garden Cafe',done:false},
  {id:4,title:'Reply to the thoughtful emails',date:todayKey,time:'15:00',tone:'coral',note:'The ones that deserve more than a quick answer',done:false}
];
let stored = JSON.parse(localStorage.getItem('daylight-tasks') || 'null');
let tasks = stored ? stored.map(task => ({...task,date:task.date || todayKey})) : starterTasks;
let selectedDate = new Date(), calendarMonth = new Date(selectedDate.getFullYear(),selectedDate.getMonth(),1), editingId = null;
const timeline = document.querySelector('#timeline'), dialog = document.querySelector('#taskDialog'), form = document.querySelector('#taskForm');
const selectedKey = () => dateKey(selectedDate);
const selectedTasks = () => tasks.filter(task => task.date === selectedKey()).sort((a,b) => a.time.localeCompare(b.time));
const save = () => localStorage.setItem('daylight-tasks',JSON.stringify(tasks));
const formatTime = time => { const [h,m] = time.split(':').map(Number); return `${String(h % 12 || 12).padStart(2,'0')}:${String(m).padStart(2,'0')} ${h >= 12 ? 'PM' : 'AM'}`; };
function escapeHTML(value) { const el=document.createElement('span'); el.textContent=value; return el.innerHTML; }
function taskHTML(task) { const tone=tones[task.tone] || tones.coral; return `<article class="task ${task.done?'done':''}" data-id="${task.id}" style="--dot:${tone.dot};--tag:${tone.tag};--tag-bg:${tone.bg}"><time class="task-time">${formatTime(task.time)}</time><span class="task-dot"></span><div class="task-card"><button class="task-check" aria-label="Toggle task completion">&#10003;</button><div class="task-main"><div class="task-title">${escapeHTML(task.title)}</div>${task.note?`<div class="task-note">${escapeHTML(task.note)}</div>`:''}</div><span class="task-tag">${tone.label}</span></div><button class="more-button" aria-label="Edit task">&middot;&middot;&middot;</button></article>`; }
function renderCalendar() {
  const month=calendarMonth.getMonth(),year=calendarMonth.getFullYear(), firstDay=new Date(year,month,1).getDay(), days=new Date(year,month+1,0).getDate(),previousDays=new Date(year,month,0).getDate();
  document.querySelector('#calendarMonth').textContent=calendarMonth.toLocaleDateString('en-US',{month:'long',year:'numeric'}); let buttons='';
  for(let i=0;i<42;i++){ const offset=i-firstDay+1, cell=offset<1?new Date(year,month-1,previousDays+offset):offset>days?new Date(year,month+1,offset-days):new Date(year,month,offset), key=dateKey(cell), count=tasks.filter(task=>task.date===key).length, classes=[cell.getMonth()!==month?'other-month':'',key===todayKey?'is-today':'',key===selectedKey()?'is-selected':'',count?'has-tasks':''].filter(Boolean).join(' '); buttons+=`<button class="calendar-day ${classes}" data-date="${key}" aria-label="${cell.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}"><span>${cell.getDate()}</span>${count?'<i></i>':''}</button>`; }
  document.querySelector('#calendarGrid').innerHTML=buttons;
}
function render() {
  const list=selectedTasks(), complete=list.filter(task=>task.done).length, percent=list.length?Math.round(complete/list.length*100):0, readable=selectedDate.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'});
  document.querySelector('#todayLabel').textContent=readable.toUpperCase(); document.querySelector('#dayTitle').innerHTML=selectedKey()===todayKey?'Make today <em>count.</em>':`Make ${selectedDate.toLocaleDateString('en-US',{weekday:'long'})} <em>count.</em>`; document.querySelector('#flowTitle').textContent=selectedKey()===todayKey?"Today's flow":`${selectedDate.toLocaleDateString('en-US',{weekday:'long'})}'s flow`;
  timeline.innerHTML=list.map(taskHTML).join(''); document.querySelector('#emptyAdd').style.display=list.length?'none':'inline-block'; document.querySelector('#taskSummary').textContent=`${list.length} task${list.length===1?'':'s'} · ${complete} complete`; document.querySelector('#progressText').textContent=`${percent}%`; document.querySelector('#ringProgress').style.strokeDashoffset=113.1-(113.1*percent/100);
  const next=list.find(task=>!task.done); document.querySelector('#nextTaskName').textContent=next?next.title:list.length?'That is everything for this day':'A clear day is waiting'; document.querySelector('#nextTaskTime').textContent=next?`${formatTime(next.time)} · ${tones[next.tone].label}`:list.length?'Take a breath - you made the time count.':`Add something to ${readable}.`; document.querySelector('#calendarInsight').innerHTML=list.length?`${list.length} thing${list.length===1?'':'s'} planned<br />for this day.<br />${complete?`${complete} already done.`:'Start with one.'}`:'Choose a day,<br />then give it<br />some intention.'; renderCalendar();
}
function openDialog(task) { editingId=task?task.id:null; document.querySelector('#dialogTitle').textContent=task?'Edit this task':'Schedule a task'; document.querySelector('#taskTitle').value=task?task.title:''; document.querySelector('#taskDate').value=task?task.date:selectedKey(); document.querySelector('#taskTime').value=task?task.time:'09:00'; document.querySelector('#taskTone').value=task?task.tone:'coral'; document.querySelector('#taskNote').value=task?task.note:''; document.querySelector('#deleteButton').style.visibility=task?'visible':'hidden'; dialog.showModal(); setTimeout(()=>document.querySelector('#taskTitle').focus(),50); }
document.querySelector('#addButton').addEventListener('click',()=>openDialog()); document.querySelector('#emptyAdd').addEventListener('click',()=>openDialog()); document.querySelector('#cancelButton').addEventListener('click',()=>dialog.close());
document.querySelector('#deleteButton').addEventListener('click',()=>{if(editingId!==null){tasks=tasks.filter(task=>task.id!==editingId);save();render();dialog.close();}});
document.querySelector('#previousMonth').addEventListener('click',()=>{calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()-1,1);renderCalendar();}); document.querySelector('#nextMonth').addEventListener('click',()=>{calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()+1,1);renderCalendar();});
function goToday(){selectedDate=new Date();calendarMonth=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),1);render();} document.querySelector('#jumpToday').addEventListener('click',goToday); document.querySelector('#todayButton').addEventListener('click',event=>{event.preventDefault();goToday();});
document.querySelector('#calendarGrid').addEventListener('click',event=>{const day=event.target.closest('.calendar-day');if(!day)return;selectedDate=new Date(`${day.dataset.date}T12:00:00`);calendarMonth=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),1);render();});
form.addEventListener('submit',event=>{event.preventDefault();const data=Object.fromEntries(new FormData(form));if(editingId===null)tasks.push({id:Date.now(),title:data.title.trim(),date:data.date,time:data.time,tone:data.tone,note:data.note.trim(),done:false});else Object.assign(tasks.find(task=>task.id===editingId),{title:data.title.trim(),date:data.date,time:data.time,tone:data.tone,note:data.note.trim()});selectedDate=new Date(`${data.date}T12:00:00`);calendarMonth=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),1);save();render();dialog.close();});
timeline.addEventListener('click',event=>{const item=event.target.closest('.task');if(!item)return;const task=tasks.find(entry=>entry.id===Number(item.dataset.id));if(event.target.closest('.task-check')){task.done=!task.done;save();render();}else if(event.target.closest('.more-button')||event.target.closest('.task-card'))openDialog(task);}); document.querySelector('#themeButton').addEventListener('click',()=>document.body.classList.toggle('dark')); render();
